### ISSUE TITLE
Displayed history of commands  causing the terminal to rewrite and breakup the existing typed text, malforming the printed output

### ISSUE THREAD

**Issue by 0x0OZ** [ohmyzsh/ohmyzsh#12645]
### Describe the bug

Text can't truly explain the issue,
![image](https://github.com/user-attachments/assets/dfffa315-35ee-4534-9ae4-438bd5ea80b7)
Now this is normal command history preview when using zsh, now if I try to keep tying and for example type localhost,
the interpreter will be malformed, and even that I added space ( and didn't remove it) it will be removed in the screen
![image](https://github.com/user-attachments/assets/061c9d9a-3bcc-4730-835e-fdffcf5c482a)
This look so wrong but it actually correct in the terminal and will be a successful command
![image](https://github.com/user-attachments/assets/e603057c-d48a-4538-a717-8303cb6e758f)

It's not terminal issue but rather it's zsh or related to the theme/plugins because I tested it with windows terminal through (ssh)

### Steps to reproduce

1. have a very large last history of some command (like multiple lines)
2. try to type something else that starts with that command
3. observe how the text is malformed

### Expected behavior

Typed text shouldn't be malformed

### OS / Linux distribution

Linux kali 6.8.11-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.8.11-1kali2 (2024-05-30) x86_64 GNU/Linux

### Zsh version

5.9

### Terminal emulator

xfce4-terminal, and windows terminal

### If using WSL on Windows, which version of WSL

None

### Additional context

My plugins:
![image](https://github.com/user-attachments/assets/0031dbd4-37d0-48e4-9ed0-6b99b27666e4)
And
ZSH_THEME="awesomepanda"

**Comment by mcornella** [comment]
Check that you're using a UTF-8 locale, see https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command.

**Comment by 0x0OZ** [comment]
> Check that you're using a UTF-8 locale, see https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#i-see-duplicate-typed-characters-after-i-complete-a-command.

Like this?
![image](https://github.com/user-attachments/assets/273d02f1-ecb6-45ee-a7a0-38ee144abda2)
That's what I currently have

**Comment by Harshchauhan64** [comment]
I have similar kind of issue: 
![image](https://github.com/user-attachments/assets/8685f728-0d62-4a36-a1e0-7e430b366d1c)
I have tried to change the locale but didnt worked.

**Comment by 0x0OZ** [comment]
It seems this issue is specific to `apple` theme

@Harshchauhan64 If you change the theme to something else I assume it should be fixed
@mcornella I think this theme is part of this repo, can you test again now but with this specific theme?

**Comment by Harshchauhan64** [comment]
I have changed to powerlevel10k but the issue still persist. I was previously on default theme (robyrussell) 
![image](https://github.com/user-attachments/assets/3da0bafc-b5f0-4be8-9f8c-8bc1639a230f)
In the img the echo cmd is repeated again and my locale are all set correctly.
![image](https://github.com/user-attachments/assets/e685bd21-2ab2-433e-acd4-9e0b51746b8b)
Honestly I don't know what is making to re prompt the cmd and the issue is not there when running tmux session.

**Comment by mcornella** [comment]
@0x0OZ make sure that the locale used is exactly as written in the output of `locale -a`.

@Harshchauhan64 your issue is different. See the resolution of #12332.

**Comment by mcornella** [comment]
@0x0OZ OK no, this is caused by commit https://github.com/ohmyzsh/ohmyzsh/commit/80c114cb3a64044ea50b623f96a35bc022db5e8d from #5982.

Those added markers makes zsh not know how many characters are inside.

@carlosala can you check this out?

**Comment by 0x0OZ** [comment]
Great, Glad to hear that the root cause is found

**Comment by mcornella** [comment]
Can you try #12651 to see if it works for you? You can do that with `omz pr test 12651`. If it doesn't, make sure that the `locale` set uses the exact UTF-8 one from `locale -a`.

**Comment by 0x0OZ** [comment]
> omz pr test 12651

That does fix it! Thank you :)
