### ISSUE TITLE
Strange completion suggestion (mismatched upper and lowercase)

### ISSUE THREAD

**Issue by manfredlotz** [ohmyzsh/ohmyzsh#8839]
I have a strange phenomenon regarding completion.

The system is Fedora 32, zsh is 5.8 and oh-my-zsh is newest.

I have a directory with the following content

```
drwxr-xr-x. 1 root root     4884 Apr 17 16:29 backups
drwxr-xr-x. 1 root root      128 Apr 10 11:25 gpg
drwxr-xr-x. 1 root root      340 Apr 17 16:29 installer
-rw-r--r--. 1 root root     1201 Apr 17  2014 README
drwxr-xr-x. 1 root root      274 Apr 10 11:25 TeXLive
-rw-r--r--. 1 root root      945 Apr 10 11:37 texlive.profile
-rw-r--r--. 1 root root 15603801 Apr 17 16:29 texlive.tlpdb
-rw-r--r--. 1 root root 16308930 Apr 17 16:28 texlive.tlpdb.3fa7fda404e9c1926412f4d43d381cc7
-rw-r--r--. 1 root root 16286175 Apr 13 08:38 texlive.tlpdb.e3a260d598eed31bbd62f419747d9e4a
-rw-r--r--. 1 root root 16260012 Apr 11 10:05 texlive.tlpdb.e838e10992a52b715be9e99422af8a05
drwxr-xr-x. 1 root root   145106 Apr 17 16:29 tlpobj
drwxr-xr-x. 1 root root      112 Apr 10 11:36 tlpostcode
drwxr-xr-x. 1 root root       36 Apr 10 11:34 tltcl
drwxr-xr-x. 1 root root      246 Apr 10 11:34 translations
```
When I now type `ls -l te` and TAB I get the following suggestion:

`ls -l teXLive`  

This is totally confusing. Watch the mixture of lower and upper case. 

Any idea?

**Comment by mcornella** [comment]
Can you try running this and seeing if completion is fixed?
``zsh
zstyle ':completion:*' matcher-list 'r:[[:ascii:]]||[[:ascii:]]=** r:|=* m:{a-z\-}={A-Z\_}'
```

**Comment by manfredlotz** [comment]
I went to the same directory and yes if I ran your suggested `zstyle...` statement then things are fixed. Thank you.

**Comment by manfredlotz** [comment]
But in the same shell where I issued your proposed zstyle command completion is broken in general when doing a `cd` command and trying completion.

**Comment by mcornella** [comment]
Yeah, I can reproduce your issue.

**Comment by iCraft85** [comment]
Zsh Version: `5.8` 

When I run `zstyle -L ':completion:*' matcher-list` this I get: `zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'`

`zstyle -L ':completion:*' matcher-list` for this when I have **case senstive** set to `true` i get `zstyle ':completion:*' matcher-list 'r:|=*' 'l:|=* r:|=*'`

My `.zshrc` aslo has this command `zstyle ':completion:*' matcher-list 'r:[[:ascii:]]||[[:ascii:]]=** r:|=* m:{a-z\-}={A-Z\_}'` which I was given in the discord by @mcornella

**Comment by mcornella** [comment]
Fixed some time ago in master.

**Comment by montyc1999** [comment]
I am still seeing this behavior, in zsh 5.9 and latest ohmyzsh.

```
touch hello
touch HELLOWORLD
cat he<TAB>
```

Produces the suggestion: `cat heLLO`
